---
title: "spmm_vs_others"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(DirichletReg)
library(tidyverse)
```

#### differences among models
```{r}


nlabel <- 3
mu <- cbind(c(-1, 0, 1), c(1, 0, 1))
mu <- mu * 10
sigma <- matrix(rep(1, 6), ncol = 2)
lambda <- 1 / (sigma ** 2)
tau <- mu / (sigma ** 2)

alpha1 <- c(1, 1, 1) / 5
alpha2 <- c(1, 1)
set.seed(0)

###
N = 1000
G1 <- rdirichlet(n = N, alpha = alpha1)
G2 <- rdirichlet(n = N, alpha = alpha2)

### LDA
x1 <- matrix(NA, ncol = 2, nrow = N)
for (i in 1:N){
  z <- sample(nlabel, size = 1, prob = G1[i,])
  for(j in 1:2){
    x1[i, j] <- rnorm(1, mean = mu[z, j], sd = sigma[z, j])
  }
}


# BPM
lambdaX <- G1 %*% lambda
tauX <- G1 %*% tau
sigmaX <- sqrt(1 / lambdaX)
muX <- tauX / lambdaX
x2 <- matrix(NA, ncol = 2, nrow = N)
for (i in 1:N){
  for(j in 1:2){
    x2[i, j] <- rnorm(1, mean = muX[i, j], sd = sigmaX[i, j])
  }
}

# sPMM
n1 <- N %/% 2
G2_trans <- matrix(rep(0, N * nlabel), nrow = N)
G2_trans[, 3] <- G2[, 2]
G2_trans[1:n1, 1] <- G2[1:n1, 1] 
G2_trans[(n1 + 1):N, 2] <- G2[(n1 + 1):N, 1]

lambdaX <- G2_trans %*% lambda
tauX <- G2_trans %*% tau
sigmaX <- sqrt(1 / lambdaX)
muX <- tauX / lambdaX
x3 <- matrix(NA, ncol = 2, nrow = N)
for (i in 1:N){
  for(j in 1:2){
    x3[i, j] <- rnorm(1, mean = muX[i, j], sd = sigmaX[i, j])
  }
}

data.frame(x = x1[,1], y = x1[,2]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(color = 'cadetblue') + 
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
ggsave("LDA.png", dpi = 300, width = 5, height = 5)
data.frame(x = x2[,1], y = x2[,2]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(color = 'green') + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
ggsave("BPM.png", dpi = 300, width = 5, height = 5)
data.frame(x = x3[,1], y = x3[,2]) %>%
  mutate(label = rep(paste("class ", 1:2), each = n1)) %>%
  ggplot(aes(x = x, y = y, color = label)) + 
  geom_point() + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = c(0.9, 0.2))
ggsave("sPMM.png", dpi = 300, width = 5, height = 5)
# dat <- rbind(x1, x2, x3) %>% 
#   as.data.frame() %>%
#   mutate(type = rep(c("LDA", "BPM", "sPMM"), each = N)) 
# colnames(dat)[1:2] = c('x', 'y')
# dat %>% ggplot(aes(x = x, y = y,color = type)) + geom_point()

```

#### prior
```{r}
N <- 1000
data.frame(p = rep(seq(0, 1, length.out = N), 3), a = rep(c(0.5, 1, 2), each = N), b = rep(c(0.5, 1, 5), each = N), prior = rep(c("(0.5, 0.5)", "(1, 1)", "(2, 5)"), each = N)) %>%
  mutate(pdf = dbeta(p, a, b)) %>%
  ggplot(aes(x = p, y = pdf, color = prior)) +
  #geom_point(size = 0.1)
  geom_line()

ggsave("prior_bernoulli.png", dpi = 300, width = 7, height = 5)
```

```{r}
set.seed(0)
N <- 1000
a <- c(0.5, 1, 2)
b <- c(0.5, 1, 5)
K <- 3
alpha2 <- c(1, 1)
G2 <- rdirichlet(n = N, alpha = alpha2)
n1 <- N %/% 2
G2_trans <- matrix(rep(0, N * nlabel), nrow = N)
G2_trans[, 3] <- G2[, 2]
G2_trans[1:n1, 1] <- G2[1:n1, 1] 
G2_trans[(n1 + 1):N, 2] <- G2[(n1 + 1):N, 1]
for (i in 1:3){
  p <- matrix(rbeta(K * 2, a[i], b[i]), ncol = 2)
  logit <- log(p / (1 - p))
  
}
```

