universe=docker
docker_image=hanyingj/pymc3-sklearn

executable=supervised.sh
transfer_input_files=/home/hjiang252/real_data/data/cleaned_data.csv, /home/hjiang252/real_data/configurations/configurations_MOFA.csv,/home/hjiang252/real_data/scripts/test.py

# requesting resources
request_memory=1GB
request_cpus=1
request_disk=1GB

# parameters
environment="id=$(Step)"

# log files
error= /home/hjiang252/real_data/res/test/err$(Process).err
output= /home/hjiang252/real_data/res/test/out$(Process).out
log= /home/hjiang252/real_data/res/test/log$(Process).log
queue 2
