---
title: "plot_Normal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(ggplot2)
```
## fix_ntopic
```{r}
res_fix_ntopic = read.csv("../data/res_fix_ntopic.csv") # read data
res_sum = apply(res_fix_ntopic, 1, function(x) c(mean(x[18:22]), mean(x[23:27]), sd(x[18:22]), sd(x[23:27]))) # calculate average accuracy and sd for all folds
res_fix_ntopic = res_fix_ntopic %>% 
  select(d, nlabel, a, supervised, unsupervised) %>%
  mutate(supervised_mean = res_sum[1,], unsupervised_mean = res_sum[2,],
               supervised_sd = res_sum[3,], unsupervised_sd = res_sum[4,])
```
```{r}
# compare stability
table(res_fix_ntopic$supervised_mean>res_fix_ntopic$unsupervised_mean)
table(res_fix_ntopic$supervised_sd<res_fix_ntopic$unsupervised_sd)
```

```{r}
res_fix_ntopic %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  ggplot(aes(x=nlabel,y=accuracy,color=log(a))) + geom_point(size=1) +
  labs(x="number of classes") + facet_grid(method ~ d,space ="free_x")
ggsave("figure1_fix_ntopic_dimension.png", dpi = 150, width = 6, height = 4)
```
## d100
```{r}
res_d100 = read.csv("../data/res_d100.csv")  # read data
res_sum = apply(res_d100, 1, function(x) c(mean(x[18:22]), mean(x[23:27]), sd(x[18:22]), sd(x[23:27]))) # calculate average accuracy and sd for all folds
res_d100 = res_d100 %>%
  select(k0, k1, nlabel, a, supervised, unsupervised) %>%
  mutate(supervised_mean = res_sum[1,], unsupervised_mean = res_sum[2,],
         supervised_sd = res_sum[3,], unsupervised_sd = res_sum[4,])
names(res_d100)[1:2] = c("class_specific_topics", "shared_topics")
```
```{r}
# compare stability
table(res_d100$supervised_mean>res_d100$unsupervised_mean)
table(res_d100$supervised_sd<res_d100$unsupervised_sd)
```
```{r}
res_d100 %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  ggplot(aes(x=nlabel,y=accuracy,color=method)) +
  geom_point(size=1) + 
  labs(x="number of classes") +
  facet_grid(shared_topics ~ class_specific_topics, labeller = label_both)
ggsave("figure2_d100_k0_k1.png", dpi = 150, width = 6, height = 4)
```
## random
```{r}
res_random = read.csv("../data/res_random.csv")

res_sum = apply(res_random ,1, function(x) c(mean(x[18:22]), mean(x[23:27]), sd(x[18:22]), sd(x[23:27]))) # calculate average accuracy and sd for all folds
table(res_sum[1,]>res_sum[2,])
table(res_sum[3,]<res_sum[4,])
res_random = res_random %>%
  select(d, k0, k1, nlabel, a, supervised, unsupervised,mu_Mu, sigma2_Mu,alpha_Lambda, beta_Lambda) %>%
  mutate(var_Mu = beta_Lambda/(alpha_Lambda-1)*sigma2_Mu,
         mean_Lambda = (alpha_Lambda-0.5)/beta_Lambda,
         mean_S = alpha_Lambda/(beta_Lambda - 1))
```
```{r}
res_random %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  #ggplot(aes(x=log(var_Mu),y=accuracy, color=method)) + 
  ggplot(aes(x=var_Mu,y=accuracy, color=method)) + 
  geom_point(size=1)


res_random %>%
  #ggplot(aes(x=log(var_Mu),y=accuracy, color=method)) + 
  ggplot(aes(x=var_Mu,y=supervised, color=log(a))) + 
  geom_point(size=1)
```
```{r}
res_random %>%
  filter(mean_S<5&mean_S>0) %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  #ggplot(aes(x=log(var_Mu),y=accuracy, color=method)) + 
  ggplot(aes(x=mean_S,y=accuracy, color=method)) + 
  geom_point(size=1)
```
```{r}
res_random %>%
  filter(sigma2_Mu<200) %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  #ggplot(aes(x=log(var_Mu),y=accuracy, color=method)) + 
  ggplot(aes(x=sigma2_Mu,y=accuracy, color=method)) + 
  geom_point(size=0.5)
```
```{r}
res=res_random %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy")

ggplot(res,aes(x=k0,y=accuracy,color=method))+geom_point()+labs(x="number of unshared topics")
ggplot(res,aes(x=k1,y=accuracy,color=method))+geom_point()+labs(x="number of shared topics")
ggplot(res,aes(x=nlabel*k0-k1,y=accuracy,color=method))+geom_point()+labs(x="k0*nlabel-k1")
ggplot(res,aes(x=d,y=accuracy,color=method))+geom_point()+labs(x="dimension of data")
ggplot(res,aes(x=nlabel,y=accuracy,color=method))+geom_point()+labs(x="number of labels")

```





