universe=docker
docker_image=hanyingj/pymc3-sklearn

executable=MCMC.sh
transfer_input_files=configurations.csv,CV.py

# requesting resources
request_memory=15GB
request_cpus=1
request_disk=15GB

# parameters
environment="id=$(Step)"

# log files
error=/home/hjiang252/normal/normal_job1/res/err/err$(Process).err
output=/home/hjiang252/normal/normal_job1/res/out/out$(Process).out
log=/home/hjiang252/normal/normal_job1/res/log/log$(Process).log
queue 510
