universe=docker
docker_image=hanyingj/pymc3-sklearn

executable=supervised.sh
transfer_input_files=/home/hjiang252/real_data/data/cleaned_data.csv, /home/hjiang252/real_data/configurations/configurations_MOFA.csv,/home/hjiang252/real_data/scripts/MOFA_supervised.py

# requesting resources
request_memory=12GB
request_cpus=1
request_disk=3GB

# parameters
environment="id=$(Step)"

# log files
error= /home/hjiang252/real_data/res/supervised/err$(Process).err
output= /home/hjiang252/real_data/res/supervised/out$(Process).out
log= /home/hjiang252/real_data/res/supervised/log$(Process).log
queue 75
