---
title: "analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r,echo=FALSE, message = FALSE, warining = FALSE}
library(data.table)
library(tidyverse)
library(purrr)
library(ggplot2)
library(ggpubr)
library(MOFA2)
library(dplyr)
```

```{r,echo=FALSE}
prediction_file = "../res/CV_res/prediction.csv" # where the prediction is saved
```

### compare the accuracy of supervised vs unsupervised
```{r,echo=FALSE}
prediction = read.csv(prediction_file) %>% 
  mutate(correct = (true == prediction),  true= factor(true), prediction = factor(prediction)) 
```
```{r,echo=FALSE, message = FALSE, warining = FALSE}
prediction %>% group_by(method, k0) %>%
  summarize(accuracy = mean(correct)) %>% 
  ggplot(aes(x = k0, y = accuracy, color = method)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)") +
  ggtitle("The accuracy of both models with different k0")
ggsave("figures/accuracy_k0.png", dpi = 300, width= 8, height = 6)

prediction %>% group_by(method, k0, true) %>%
  summarize(accuracy = mean(correct)) %>%
  mutate(true = factor(true, labels = c("sepsis", "nonsepsis_ICU", "healthy", "healthy_antibiotics"))) %>%
  ggplot(aes(x = k0, y = accuracy, color = true, linetype = method)) +
  geom_line() +
  ggtitle("The accuracy of both model on different categories")
ggsave("figures/accuracy_k0_perclass.png", dpi = 300, width= 8, height = 6)

```
```{r,echo=FALSE, message = FALSE, warining = FALSE}
prediction %>% group_by(method, k0, true) %>%
  summarize(accuracy = mean(correct)) %>% 
  ggplot(aes(x = k0, y = accuracy, color = true)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)") +
  facet_grid(~method) 
```

```{r,echo=FALSE, message = FALSE, warining = FALSE}
prediction %>% group_by(method, k0, prediction) %>%
  summarize(frequency = length(prediction))%>% 
  ggplot(aes(x = k0, y = frequency, color = prediction)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)") +
  facet_grid(~method) 
```


### analyze the memberships
```{r,echo=FALSE, message = FALSE,warning = FALSE}
metadata <- fread("ftp://ftp.ebi.ac.uk/pub/databases/mofa/microbiome/metadata.txt.gz")
metadata = metadata %>% filter(sample!="TKI_F22" & sample != "TKI_F56") %>%
  select(sample,Age,Sexs,Category)
```
```{r,echo = FALSE}
dat = read.csv("../data/cleaned_data.csv")
```

```{r,echo=FALSE}
# choose a result to analyze
k0 = 10 # 1-15
G_file = paste("../res/wholeset_res/supervised_",as.character(k0),"_G.txt",sep = "")
U_file = paste("../res/wholeset_res/unsupervised_",as.character(k0),"_U.txt",sep = "")
U_su_file = paste("../res/wholeset_res/supervised_",as.character(k0),"_U.txt",sep = "")
G = read.csv(G_file,header=FALSE)
U_supervised = read.csv(U_su_file,header=FALSE)
U = read.csv(U_file,header=FALSE)
```
```{r,echo = FALSE}
G %>%  pivot_longer(everything(), names_to="topic", values_to="membership") %>%
  ggboxplot(x="topic", y = "membership") +
   ggtitle("G")
U %>%  pivot_longer(everything(), names_to="topic", values_to="membership") %>%
  ggboxplot(x="topic", y = "membership") +
  ggtitle("U")
U_supervised %>%  pivot_longer(everything(), names_to="topic", values_to="membership") %>%
  ggboxplot(x="topic", y = "membership") +
  ggtitle("U supervised")

```

Select the topics with average membebrship > 1/dim(membership)/5.

```{r,echo = FALSE}
col_G = c()
col_U = c()
col_U_su = c()
dg = length(G)
du = length(U)
k = 5
for (i in 1:dg){
  if (mean(G[[i]])>1/dg/k){
    col_G = c(col_G,i)
  }
}
for (i in 1:du){
  if (mean(U[[i]])>1/du/k){
    col_U = c(col_U,i)
  }
  if (mean(U_supervised[[i]])>1/du/k){
    col_U_su = c(col_U_su,i)
  }
}

G[col_G] %>% mutate(sample = dat$sample) %>%
  merge(metadata,by="sample",sort=FALSE)%>% 
  pivot_longer(starts_with("V") , names_to="topic", values_to="membership") %>%
  ggboxplot(x="topic", y = "membership", color="Sexs")  +
  ggtitle("G")

U[col_U] %>% mutate(sample = dat$sample) %>%
  merge(metadata,by="sample",sort=FALSE)%>% 
  pivot_longer(starts_with("V") , names_to="topic", values_to="membership") %>%
  ggboxplot(x="topic", y = "membership", color="Sexs")  +
  ggtitle("U")

U_supervised[col_U_su]%>% mutate(sample = dat$sample) %>%
  merge(metadata,by="sample",sort=FALSE)%>% 
  pivot_longer(starts_with("V") , names_to="topic", values_to="membership") %>%
  ggboxplot(x="topic", y = "membership", color="Sexs") +
  ggtitle("U supervised")

```

### simulated result

```{r, echo = FALSE}
k0 = 10
dat = read.csv("../data/cleaned_data.csv")

su_file = paste("../res/simulated/supervised_", as.character(k0), ".csv", sep = "")
un_file = paste("../res/simulated/unsupervised_", as.character(k0), ".csv", sep = "")
supervised = read.csv(su_file, header = FALSE)
unsupervised = read.csv(un_file, header = FALSE)

supervised$Category = sapply(supervised$V241, FUN = function(x) dat$Category[x+1])
unsupervised$Category = sapply(unsupervised$V241, FUN = function(x) dat$Category[x+1])
supervised$method = "supervised"
unsupervised$method = "unsupervised"
d1=rbind(supervised,unsupervised)%>% select(!V241)
dat1 = dat %>% select(!sample)%>%
  mutate(method="True_value")
colnames(dat1)[1:240] = paste("V",1:240, sep="")
dat1 = rbind(d1,dat1)
```

```{r, echo = FALSE}
fea = sample(1:240, 3, replace=F)
dat2 = dat1[c(fea,241,242)]
dat2 %>% pivot_longer(starts_with("V"), names_to="feature", values_to = "observation") %>% ggplot(aes(x=observation, color = method)) +
  geom_density()+
  facet_grid(Category~feature)
```
```{r, echo = FALSE}
fea = sample(1:240, 3, replace=F)
dat2 = dat1[c(fea,241,242)]
dat2 %>% pivot_longer(starts_with("V"), names_to="feature", values_to = "observation") %>% ggplot(aes(x=observation, color = method)) +
  geom_density()+
  facet_grid(Category~feature)
```
```{r, echo = FALSE}
fea = sample(1:240, 3, replace=F)
dat2 = dat1[c(fea,241,242)]
dat2 %>% pivot_longer(starts_with("V"), names_to="feature", values_to = "observation") %>% ggplot(aes(x=observation, color = method)) +
  geom_density()+
  facet_grid(Category~feature)
```
```{r, echo = FALSE}
fea = sample(1:240, 3, replace=F)
dat2 = dat1[c(fea,241,242)]
dat2 %>% pivot_longer(starts_with("V"), names_to="feature", values_to = "observation") %>% ggplot(aes(x=observation, color = method)) +
  geom_density()+
  facet_grid(Category~feature)
```
```{r, echo = FALSE}
fea = sample(1:240, 3, replace=F)
dat2 = dat1[c(fea,241,242)]
dat2 %>% pivot_longer(starts_with("V"), names_to="feature", values_to = "observation") %>% ggplot(aes(x=observation, color = method)) +
  geom_density()+
  facet_grid(Category~feature)
```
```{r, echo = FALSE}
fea = sample(1:240, 3, replace=F)
dat2 = dat1[c(fea,241,242)]
dat2 %>% pivot_longer(starts_with("V"), names_to="feature", values_to = "observation") %>% ggplot(aes(x=observation, color = method)) +
  geom_density()+
  facet_grid(Category~feature)
```


#### dominant
```{r}
# check whether U tend to be 
k0 = 1
su_res_folder <- sprintf("../res/submit_CHTC/supervised/wholeset/model%s/", k0)
un_res_folder <- sprintf("../res/submit_CHTC/unsupervised/wholeset/model%s/", k0)
G <- read.csv(paste0(su_res_folder, "G.csv"), header = F)
U <- read.csv(paste0(un_res_folder, "U.csv"), header = F)
U_su <- read.csv(paste0(su_res_folder, "U.csv"), header = F)
U_un <- read.csv(paste0(un_res_folder, "U_prediction.csv"), header = F)
dat <- read.csv('../data/cleaned_data.csv')
G$sample <- dat$sample
U$sample <- dat$sample
U_su$sample <- dat$sample
U_un$sample <- dat$sample

dat$Category <- factor(dat$Category, labels = c("sepsis", "nonsepsis_ICU", "healthy", "healthy_antibiotics"))
G$Category <- dat$Category
U$Category <- dat$Category
U_su$Category <- dat$Category
U_un$Category <- dat$Category

p_membership <- function(x){
  p = x %>% pivot_longer(cols = -c("sample", "Category"), names_to = "topic", values_to = "membership") %>%
    ggplot(aes(x = topic, y = sample, fill = membership)) +
    facet_grid(Category~.,scales="free_y")+
    #coord_flip() +
    
    geom_tile()
  print(p)
}
p_membership(G)
p_membership(U)
p_membership(U_su)
ggsave("figures/G_unsupervised1.png", dpi = 300, width = 8, height = 6)
p_membership(U_un)
ggsave("figures/U_1.png", dpi = 300, width = 8, height = 6)
```

```{r}
taxa = colnames(dat)[2:241]
sim_su <- read.csv("simulated/supervised1.csv", header = F) 
sim_un <- read.csv("simulated/unsupervised1.csv", header = F) 
colnames(sim_su) = taxa
colnames(sim_un) = taxa
set.seed(0)
ntaxa = 30
plot_taxa = sample(taxa, ntaxa)
sim_su[,c("sample", "Category")] = dat[,c("sample", "Category")]
sim_un[,c("sample", "Category")] = dat[,c("sample", "Category")]

rare_sample = dat$sample[dat$Category %in% c("nonsepsis_ICU","healthy_antibiotics")]
plot_frame = function(x, type){
  x %>% 
    pivot_longer(cols = -c("sample", "Category"), names_to = "feature", values_to = "value") %>% 
    mutate(type = type)%>%
    filter(sample %in% rare_sample) %>%
    filter(feature %in% plot_taxa)
}
  
t1 = plot_frame(dat, 'Truth')
t2 = plot_frame(sim_su, 'sPMM')
t3 = plot_frame(sim_un, 'BPM')

rbind(t1, t2, t3) %>% ggplot(aes(x = sample, y = feature, fill = value)) +
  facet_wrap(.~type)+
  geom_tile()



```

```{r}
t11 = pivot_wider(t1, id_cols = 'sample', names_from = "feature", values_from = "value")
t21 = pivot_wider(t2, id_cols = 'sample', names_from = "feature", values_from = "value")
t31 = pivot_wider(t3, id_cols = 'sample', names_from = "feature", values_from = "value")

d_su = t21
for(i in plot_taxa){
  d_su[,i] = d_su[,i] - t11[, i]
}
d_un = t31
for(i in plot_taxa){
  d_un[,i] = d_un[,i] - t11[, i]
}
tem = d_su %>% pivot_longer(cols = -c("sample"), names_to = "feature", values_to = "value") %>%
  mutate(type = "sPMM") %>%
  rbind(d_un %>% pivot_longer(cols = -c("sample"), names_to = "feature", values_to = "value") %>%
  mutate(type = "BPM")) 
dif = abs(tem$value)
min(dif)
max(dif)
# tem$diff = case_when(
#   dif < -5 ~ "< -"
# )
round(dif)
tem%>%
  mutate(diff = round(abs(value) %/% 3)) %>%
  mutate(difference = factor(diff, levels = 0:5, labels = c("<3", "3-6", "6-9", "9-12", "12-15", ">15"), ordered = T)) %>%
    ggplot(aes(x = sample, y = feature, fill =difference)) +
    facet_wrap(.~type) +
    geom_tile()
ggsave("figures/difference.png", dpi = 300, width = 8, height = 6)

```


```{r}
sim_su <- read.csv("simulated/supervised1.csv", header = F) %>% data.matrix()
sim_un <- read.csv("simulated/unsupervised1.csv", header = F)  %>% data.matrix()
image(
    t(data.matrix(dat[2:241])), # image() has some weird opinions about how your matrix will be plotted
    axes = FALSE,
    col = colorRampPalette(c("white", "darkorange", "black"))(30), # our colour palette
    breaks = c(seq(0, 3, length.out = 30), 100) # colour-to-value mapping
)
image(
    t(sim_su), # image() has some weird opinions about how your matrix will be plotted
    axes = FALSE,
    col = colorRampPalette(c("white", "darkorange", "black"))(30), # our colour palette
    breaks = c(seq(0, 3, length.out = 30), 100) # colour-to-value mapping
)
image(
    t(sim_un), # image() has some weird opinions about how your matrix will be plotted
    axes = FALSE,
    col = colorRampPalette(c("white", "darkorange", "black"))(30), # our colour palette
    breaks = c(seq(0, 3, length.out = 30), 100) # colour-to-value mapping
)
```
```{r}
suppressPackageStartupMessages(library(dplyr))
library(purrr)
Ncol <- 50
genmat <- map(
    1:20000,
    function(i) {
        runif(Ncol) + c(sort(abs(rnorm(50)))[1:25], rev(sort(abs(rnorm(50)))[1:25]))  * i/5000
    }
) %>% do.call(rbind, .)
image(
    t(genmat), # image() has some weird opinions about how your matrix will be plotted
    axes = FALSE,
    col = colorRampPalette(c("white", "darkorange", "black"))(30), # our colour palette
    breaks = c(seq(0, 3, length.out = 30), 100) # colour-to-value mapping
)
box()
```

