---
title: "analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r,echo=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
dat = read.csv("../data/cleaned_data.csv")

```

## compare accuracy
```{r,echo=FALSE}
accuracy = read.csv("./accuracy/accuracy.csv")
accuracy %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  ggplot(aes(x = number_of_topic,y = accuracy, color = method)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)")
```
```{r,echo=FALSE}
accuracy = read.csv("./accuracy/accuracy_per_patient.csv")
accuracy %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  ggplot(aes(x = no,y = accuracy, color = method)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)")
```
```{r}
#prediction = read.csv("./accuracy/prediction.csv")
head(prediction)
acc = data.frame(index=rep(c(1:57),2),method = c(rep("supervised", 57),rep("unsupervised", 57)),accuracy=rep(0,57*2))
for (i in 1:length(prediction[[1]])){
  if (prediction$true[i]==prediction$prediction[i]){
    if (prediction$method[i]=="supervised"){
      acc$accuracy[prediction$index[i]+1] = acc$accuracy[prediction$index[i]+1] + 1
    } else{
      acc$accuracy[prediction$index[i]+58] = acc$accuracy[prediction$index[i]+58] + 1
    }
  }
}
acc$accuracy = acc$accuracy/15
accuracy %>%
  pivot_longer(supervised:unsupervised, names_to = "method", values_to = "accuracy") %>%
  ggplot(aes(x = no,y = accuracy, color = method)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)")
acc%>%
  ggplot(aes(x = index,y = accuracy, color = method)) +
  geom_point(size=0.7) +
  labs(x="k0 (k1=k0)")
```


## simulated data

## 

```{r}
prediction %>% filter(index==1 & method=="supervised")
```


